<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?> 
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?> 
</div>
<?php //echo $this->getChildHtml('smartwave_blog_comments_toolbar'); ?>
<div class="posts-wrap karpal">

	<?php 
	$i = 1;
	foreach ($posts as $post): 
	if($i>4) { break; }
	$i = $i + 1;
	?>
    <div class="col-sm-3">
		<div class="ca-menu">
        <?php if($banner_content = $post->getBannerContent()): ?>
        <div class="postBanner">
        <?php
            echo $banner_content;
        ?>
        </div>
        <?php endif; ?>
        
		<div class="post-image">
                <?php
                    if($post_image = $post->getImage()){
                ?>
                    <a href="<?php echo $post->getAddress(); ?>" >
					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$post_image; ?>" alt=""/>
				</a>
                <?php
                    }
                ?>
		</div>
		<div style="overflow:hidden;position:relative">
        <div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
        </div>
		</div>
        <div class="postContent">
		<?php 
		$des = $post->getPostContent();//substr(, 0, 250);
		echo substr(strip_tags($des), 0, 185).'......'; 		 
		?><br>
		<a class="readmore" href="<?php echo $post->getAddress(); ?>"><?php echo $this->__("Read more >");?></a>
		</div>
		
</div>
        
        <?php echo $this->getBookmarkHtml($post) ?>
    </div>
<?php endforeach; ?>
</div>
<?php //echo $this->getChildHtml('smartwave_blog_comments_toolbar'); ?>
