<style type="text/css">
.store-button{float:right;border:2px solid #9c6051;padding:5px}
.store-location{position: relative; float: right; width: 98%; margin-right: 12px; max-width: 520px;}
.header-location-nearby-stores{background-color:rgba(0,0,0,0.9);color:#fff;overflow:hidden;max-width:500px;width:100%}
.store-location #hideMe{position: absolute; right: 0px; display: none; top: 27px;}
.location-near-by-store, .location-near-by-store-locator{float:left;width:40%;height: 405px;overflow-x: hidden;}
.location-near-by-store{background-color:rgba(0,0,0,0.1)}
.location-near-by-store-locator{width:60%}
.header-location-nearby-stores ul li:nth-child(1){border-bottom: 3px solid #3e3e3e;color: #fff;font-family: Museo-500;font-size: 0.813em;}
.header-location-nearby-stores ul li:nth-child(2), .header-location-nearby-stores ul li:nth-child(5) {font-family: Museo-500;font-size: 0.813em;}
.header-location-nearby-stores ul li:nth-child(4) {border-bottom: 3px solid #3e3e3e;}
.header-location-nearby-stores li.nearby-title {padding-bottom: 4px !important;padding-top: 6px !important;}
.header-location-nearby-stores ul li {padding: 0 3.8%;}
.header-location-nearby-stores ul{padding:0 10px;margin:0}
.header-location-nearby-stores ul li {color: #fff9d8;list-style:none;line-height:18px;padding:5px 0;font-family: Museo-500;font-size: 0.688em;text-decoration: none;width: 90%;}
.header-location-nearby-stores ul li span {color: #fff;}
.header-location-nearby-stores p{margin:0}
.location-near-by-store .near-bystore-address {padding-bottom: 0;padding-top: 0;}
 .location-near-by-store-locator table {margin: 0 auto;width: 93%;border-collapse: collapse;border-spacing: 0;}
.location-near-by-store-locator table tr {font-family: Museo-500;font-size: 0.75em;border-bottom: 3px solid #3e3e3e;color: #fff;}
.location-near-by-store-locator table tr:first-child td {padding-bottom: 0;padding-top: 5px;}
.location-near-by-store-locator table tr td {padding-bottom: 7px;padding-left: 5px;padding-top: 13px;vertical-align: top;line-height:18px}
.location-near-by-store-locator table tr td a {color: #fff9d8;font-family: Museo-500;font-size: 0.97em;padding-left: 0;}
.location-near-by-store-locator table tr td a.header-change-location {font-weight: 700;}
.store-location #hideMe a{cursor:pointer}
</style>

<script>
function toggle_visibility(id) {
    var e = document.getElementById(id);
    if (e.style.display == 'block' || e.style.display=='') e.style.display = 'none';
    else e.style.display = 'block';
}
</script>