<?php $menuHelper = Mage::helper('megamenu'); ?>
<?php $menuData = $menuHelper->getMenuData(); extract($menuData); ?>
<div class="header-wrapper">
<div class="main-nav">
    <div class="container">            
        <div class="menu-wrapper">
            <div class="menu-all-pages-container">
                <ul class="menu">
                    <?php echo $menuHelper->getMenuContent(); ?>
                </ul>
            </div>
        </div>
    </div>
</div>

</div>
		<?php
		
		$user_ip = getUserIP();
		$user_ip = "173.252.110.27";
		$useriplocation = ip_info($user_ip, "Location");

		$latitude = $useriplocation["latitude"];
        $longitude = $useriplocation["longitude"]; 
  
        

        
		$collection = Mage::getModel('storepickup/store')->getCollection();
		$allstores = $collection->toArray();
		
        $allstoresnewdata = array();
        if(isset($allstores["items"]))
        {
		   foreach($allstores["items"] as $key => $val)
		   { 
             
		     $val["storedistancefromuser"] = round(distance($latitude, $longitude, $val["store_latitude"], $val["store_longitude"], "M"), 2);

		     $allstoresnewdata[] = $val;
			 
			 
			} 
		 } 
        

 		$storedistancesfromuser = array();

  
		if(isset($allstoresnewdata))
		{ 
			foreach($allstoresnewdata as $key => $val)
			{
     			$storedistancesfromuser[] = $val["storedistancefromuser"];

 			}

 			array_multisort($storedistancesfromuser, SORT_ASC, $allstoresnewdata);
		} 	

  



		?>
		<h3>Location : </h3>
		<select>
			<?php if(isset($allstoresnewdata)){ ?>
			<?php foreach($allstoresnewdata as $key => $val){ $data = $val["store_name"]." ".$val["address"]." ".$val["city"]." ".$val["state"]." (".$val["storedistancefromuser"]." Miles)"; ?>
				<option value="<?php echo $val["store_id"]; ?>"><?php echo $data; ?></option>
			<?php } ?>	
			<?php } ?>
		</select>
<script type="text/javascript">
//<![CDATA[
var SW_MENU_POPUP_WIDTH = <?php echo $_popupWidth; ?>;
//]]>
</script>