<?php $menuHelper = Mage::helper('megamenu'); ?>
<?php $menuData = $menuHelper->getMenuData(); extract($menuData); ?>
<div class="header-wrapper">
<div class="main-nav">
    <div class="container">            
        <div class="menu-wrapper">
            <div class="menu-all-pages-container">
                <ul class="menu">
                    <?php echo $menuHelper->getMenuContent(); ?>
                </ul>
            </div>
        </div>
    </div>
</div>

</div>
		<?php
			    $collection = Mage::getModel('storepickup/store')->getCollection();
				$a = $collection->toArray();
				//echo "<pre>";
				//print_r($a);
				//die;

		?>
		<h3>Location : </h3>
		<select>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
<script type="text/javascript">
//<![CDATA[
var SW_MENU_POPUP_WIDTH = <?php echo $_popupWidth; ?>;
//]]>
</script>