<?php $menuHelper = Mage::helper('megamenu'); ?>
<?php $menuData = $menuHelper->getMenuData(); extract($menuData); ?>
<div class="header-wrapper">
<div class="main-nav">
    <div class="container">            
        <div class="menu-wrapper">
            <div class="menu-all-pages-container">
                <ul class="menu">
                    <?php echo $menuHelper->getMenuContent(); ?>
                </ul>
            </div>
        </div>
    </div>
</div>

</div>
		<?php
			    $collection = Mage::getModel('storepickup/store')->getCollection();
				$allstores = $collection->toArray();
				

		?>
		<h3>Location : </h3>
		<select>
			<?php if(isset($allstores["items"])){ ?>
			<?php foreach($allstores["items"] as $key => $val){ $data = $val["store_name"]." ".$val["address"]." ".$val["city"]." ".$val["state"]; ?>
				<option value="<?php echo $val["store_id"]; ?>"><?php echo $data; ?></option>
			<?php } ?>	
			<?php } ?>
		</select>
<script type="text/javascript">
//<![CDATA[
var SW_MENU_POPUP_WIDTH = <?php echo $_popupWidth; ?>;
//]]>
</script>